-- V5: 챌린지 이미지 심사 거부 알림 타입 추가 (심사 개편 — 이미지 거부 = 이미지 삭제 + 방장 알림)
ALTER TABLE `Notification`
    MODIFY COLUMN `type` enum('NICKNAME_REJECTED','PROFILE_IMAGE_REJECTED','CHALLENGE_NAME_REJECTED',
        'CHALLENGE_IMAGE_REJECTED','CHALLENGE_CLOSED','CHALLENGE_APPROVED','CHALLENGE_JOIN_REQUESTED',
        'CHALLENGE_MEMBER_APPROVED','CHALLENGE_MEMBER_REJECTED','FALLBACK_APPROVED','FALLBACK_REJECTED',
        'WATCHER_ROUTINE_FAILED','NOTICE_CREATED','SYSTEM')
        CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
