-- ======================================================================
-- score — 점수·티어 원장
--
-- 이 파일은 한 도메인의 표를 모아 둔다. 파일 안의 순서는 외래키 방향이고,
-- 파일 사이의 순서도 같다 — 앞 파일만 뒤 파일을 가리킨다.
-- ======================================================================

CREATE TABLE `user_score_summaries` (
  `user_id` binary(16) NOT NULL,
  `total_score` int NOT NULL DEFAULT '10',
  `actual_tier` varchar(10) NOT NULL DEFAULT 'BRONZE',
  `display_tier` varchar(10) NOT NULL DEFAULT 'BRONZE',
  `version` bigint NOT NULL DEFAULT '0',
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`user_id`),
  KEY `idx_user_score_summaries_ranking` (`total_score` DESC,`user_id`),
  KEY `idx_user_score_summaries_tier_ranking` (`display_tier`,`total_score` DESC,`user_id`),
  KEY `idx_summary_tier_ranking` (`display_tier`,`total_score` DESC,`user_id`),
  CONSTRAINT `fk_user_score_summaries_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `ck_score_range` CHECK ((`total_score` between 0 and 2000))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='사용자 현재 점수 및 티어';

CREATE TABLE `score_transactions` (
  `id` binary(16) NOT NULL,
  `user_id` binary(16) NOT NULL,
  `entry_kind` varchar(10) NOT NULL,
  `reason` varchar(32) NOT NULL,
  `source_type` varchar(32) NOT NULL,
  `source_event_key` char(64) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `source_version` int unsigned DEFAULT NULL,
  `processing_key` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `idempotency_key` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `effective_at` datetime(3) NOT NULL,
  `effective_order` varbinary(128) NOT NULL,
  `policy_version` varchar(32) DEFAULT NULL,
  `auth_type` varchar(10) DEFAULT NULL,
  `challenge_id` binary(16) DEFAULT NULL,
  `cycle_id` binary(16) DEFAULT NULL,
  `incident_type` varchar(32) DEFAULT NULL,
  `raw_delta` int NOT NULL,
  `limited_delta` int NOT NULL,
  `applied_delta` int NOT NULL,
  `balance_after` int NOT NULL,
  `actual_tier_after` varchar(10) NOT NULL,
  `display_tier_after` varchar(10) NOT NULL,
  `reversal_of` binary(16) DEFAULT NULL,
  `replacement_of` binary(16) DEFAULT NULL,
  `payload_json` json NOT NULL,
  `created_at` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_score_idempotency` (`idempotency_key`),
  UNIQUE KEY `uq_score_reversal` (`reversal_of`),
  UNIQUE KEY `uq_score_replacement` (`replacement_of`),
  KEY `idx_score_user_history` (`user_id`,`created_at` DESC,`id` DESC),
  KEY `idx_score_replay` (`user_id`,`effective_at`,`effective_order`),
  KEY `idx_score_source` (`user_id`,`source_event_key`,`source_version`),
  KEY `idx_score_processing` (`user_id`,`processing_key`,`id`),
  KEY `idx_score_cycle` (`user_id`,`challenge_id`,`cycle_id`),
  CONSTRAINT `fk_score_transaction_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`),
  CONSTRAINT `ck_score_balance` CHECK ((`balance_after` between 0 and 2000)),
  CONSTRAINT `ck_score_commit_zero` CHECK (((`entry_kind` <> _utf8mb4'COMMIT') or ((`raw_delta` = 0) and (`limited_delta` = 0) and (`applied_delta` = 0)))),
  CONSTRAINT `ck_score_entry_kind` CHECK ((`entry_kind` in (_utf8mb4'RESULT',_utf8mb4'REVERSAL',_utf8mb4'COMMIT'))),
  CONSTRAINT `ck_score_incident_cycle` CHECK (((`incident_type` is null) or (`cycle_id` is null))),
  CONSTRAINT `ck_score_replacement_kind` CHECK (((`replacement_of` is null) or (`entry_kind` = _utf8mb4'RESULT'))),
  CONSTRAINT `ck_score_reversal_link` CHECK ((((`entry_kind` = _utf8mb4'REVERSAL') and (`reversal_of` is not null) and (`replacement_of` is null)) or ((`entry_kind` <> _utf8mb4'REVERSAL') and (`reversal_of` is null))))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `cycle_score_states` (
  `user_id` binary(16) NOT NULL,
  `challenge_id` binary(16) NOT NULL,
  `cycle_id` binary(16) NOT NULL,
  `cycle_start_on` date NOT NULL,
  `cycle_end_on` date NOT NULL,
  `membership_joined_at_snapshot` datetime(3) NOT NULL,
  `policy_version` varchar(32) NOT NULL,
  `tier_snapshot` varchar(10) NOT NULL,
  `target_count` tinyint unsigned NOT NULL,
  `success_weight` smallint unsigned NOT NULL,
  `miss_weight` smallint unsigned NOT NULL,
  `success_count` tinyint unsigned NOT NULL DEFAULT '0',
  `miss_count` tinyint unsigned NOT NULL DEFAULT '0',
  `raw_cumulative` int NOT NULL DEFAULT '0',
  `limited_cumulative` int NOT NULL DEFAULT '0',
  `cycle_result` varchar(10) DEFAULT NULL,
  `success_streak_after` int unsigned DEFAULT NULL,
  `failure_streak_after` int unsigned DEFAULT NULL,
  `closed_at` datetime(3) DEFAULT NULL,
  `version` bigint NOT NULL DEFAULT '0',
  PRIMARY KEY (`user_id`,`challenge_id`,`cycle_id`),
  UNIQUE KEY `uq_cycle_period` (`user_id`,`challenge_id`,`cycle_start_on`),
  KEY `idx_cycle_open` (`closed_at`,`challenge_id`,`cycle_id`),
  CONSTRAINT `fk_cycle_score_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`),
  CONSTRAINT `ck_cycle_close_state` CHECK ((((`closed_at` is null) and (`cycle_result` is null) and (`success_streak_after` is null) and (`failure_streak_after` is null)) or ((`closed_at` is not null) and (`cycle_result` is not null) and (`cycle_result` in (_utf8mb4'SUCCESS',_utf8mb4'PARTIAL',_utf8mb4'FAILURE',_utf8mb4'INVALID')) and (`success_streak_after` is not null) and (`failure_streak_after` is not null)))),
  CONSTRAINT `ck_cycle_counts` CHECK (((`success_count` <= `target_count`) and (`miss_count` <= `target_count`) and ((`success_count` + `miss_count`) <= `target_count`))),
  CONSTRAINT `ck_cycle_limit` CHECK ((`limited_cumulative` between -(20) and 20)),
  CONSTRAINT `ck_cycle_target` CHECK ((`target_count` between 1 and 7))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
